# Generated by Django 5.1.6 on 2025-02-22 21:38

from django.db import migrations

#migration needed for change require on database
def populate_status(apps, schemaeditor):
    entries={
        "published": "A post that is visible to all",
        "draft":"A post not yet ready to be published",
        "archived":"An older post, for logged in users"
    }
    Status =apps.get_model("posts","Status")
    for key, value in entries.items():
        status_obj=Status(name=key, description=value) #action in memory
        status_obj.save() #save in databse


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_status_post_status'),
    ]

    operations = [
        migrations.RunPython(populate_status)
    ]
